baseURL = 'https://ConorReynolds.github.io'
languageCode = 'en-gb'
title = 'Conor Reynolds'
theme = [ "hugo-researcher" ]
math = true

[params]
    author = "Conor Reynolds"
    js = [ "font-size.js" ]
    # css = ["static/lasndasd.css"]
    [params.footer]
        text = "Â© 2022 Conor Reynolds"
        url = "https://github.com/ConorReynolds"
    [params.style]
        fontFamily = "Charter"
        pageWidth = "650px"
        avatarSize = "90px"
        colorBlack = "#222222"
        colorRed = "#933"
    [[params.socialIcons]]
        icon = "fab fa-github"
        title = "GitHub"
        url = "https://github.com/ConorReynolds"
    [[params.socialIcons]]
        icon = "fab fa-gitlab"
        title = "GitHub"
        url = "https://gitlab.cs.nuim.ie/creynolds"
    [[params.socialIcons]]
        icon = "fas fa-envelope"
        title = "Email"
        url = "mailto:conor.reynolds@mu.ie"


[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "CV"
    url = "/cv"
    weight = 2
#   [[menu.main]]
#     name = "Resume"
#     url = "/resume.pdf"
#     # 'pre' and 'post' hooks are available
#     # here we use an icon from Bootstrap https://icons.getbootstrap.com/
#     pre = '<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-file-earmark-person-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M2 2a2 2 0 0 1 2-2h5.293A1 1 0 0 1 10 .293L13.707 4a1 1 0 0 1 .293.707V14a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V2zm7.5 1.5v-2l3 3h-2a1 1 0 0 1-1-1zM11 8a3 3 0 1 1-6 0 3 3 0 0 1 6 0zm2 5.755S12 12 8 12s-5 1.755-5 1.755V14a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1v-.245z"/></svg> '
#     weight = 2
  [[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 3



[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    noHl = false
    style = 'github'
    tabWidth = 2

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files
